
//! Autogenerated weights for `pallet_node_manager`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 43.1.0
//! DATE: 2026-10-08, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `ip-172-31-81-169`, CPU: `AMD EPYC 7R32`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// ./predictor-node
// benchmark
// pallet
// --pallet
// pallet_node_manager
// --runtime
// ./predictor_runtime.compact.wasm
// --genesis-builder=runtime
// --wasm-execution=compiled
// --extrinsic
// *
// --steps=50
// --repeat=20
// --output
// /home/ubuntu/output/weights.rs
// --template
// ./frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_node_manager`.
pub trait WeightInfo {
	fn register_node() -> Weight;
	fn register_reserved_node() -> Weight;
	fn set_admin_config_registrar() -> Weight;
	fn set_admin_config_reward_period() -> Weight;
	fn set_admin_config_reward_batch_size() -> Weight;
	fn set_admin_config_reward_heartbeat() -> Weight;
	fn set_reward_amount() -> Weight;
	fn set_admin_config_reward_enabled() -> Weight;
	fn set_admin_config_min_threshold() -> Weight;
	fn on_initialise_with_new_reward_period() -> Weight;
	fn on_initialise_no_reward_period() -> Weight;
	fn offchain_submit_heartbeat() -> Weight;
	fn heartbeat_for_owned_nodes(b: u32, ) -> Weight;
	fn top_up_reward_pot() -> Weight;
	fn deregister_nodes(b: u32, ) -> Weight;
	fn update_signing_key() -> Weight;
	fn pay_one_node() -> Weight;
	fn complete_reward_period() -> Weight;
	fn set_admin_config_lock_schedule() -> Weight;
	fn set_admin_config_forfeiture_destination() -> Weight;
	fn set_admin_config_reserve_nodes(b: u32, ) -> Weight;
	fn withdraw_rewards() -> Weight;
}

/// Weights for `pallet_node_manager` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `NodeManager::NodeRegistrar` (r:1 w:0)
	/// Proof: `NodeManager::NodeRegistrar` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::NodeRegistry` (r:1 w:1)
	/// Proof: `NodeManager::NodeRegistry` (`max_values`: None, `max_size`: Some(116), added: 2591, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::SigningKeyToNodeId` (r:1 w:1)
	/// Proof: `NodeManager::SigningKeyToNodeId` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::ReservedNodes` (r:1 w:0)
	/// Proof: `NodeManager::ReservedNodes` (`max_values`: None, `max_size`: Some(112), added: 2587, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::TotalRegisteredNodes` (r:1 w:1)
	/// Proof: `NodeManager::TotalRegisteredNodes` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::TotalReservedNodes` (r:1 w:0)
	/// Proof: `NodeManager::TotalReservedNodes` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::OwnedNodesCount` (r:1 w:1)
	/// Proof: `NodeManager::OwnedNodesCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::NextNodeSerialNumber` (r:1 w:1)
	/// Proof: `NodeManager::NextNodeSerialNumber` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::OwnedNodes` (r:0 w:1)
	/// Proof: `NodeManager::OwnedNodes` (`max_values`: None, `max_size`: Some(96), added: 2571, mode: `MaxEncodedLen`)
	fn register_node() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `221`
		//  Estimated: `3581`
		// Minimum execution time: 53_072_000 picoseconds.
		Weight::from_parts(54_131_000, 3581)
			.saturating_add(T::DbWeight::get().reads(8_u64))
			.saturating_add(T::DbWeight::get().writes(6_u64))
	}
	/// Storage: `NodeManager::NodeRegistrar` (r:1 w:0)
	/// Proof: `NodeManager::NodeRegistrar` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::NodeRegistry` (r:1 w:1)
	/// Proof: `NodeManager::NodeRegistry` (`max_values`: None, `max_size`: Some(116), added: 2591, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::SigningKeyToNodeId` (r:1 w:1)
	/// Proof: `NodeManager::SigningKeyToNodeId` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::ReservedNodes` (r:1 w:1)
	/// Proof: `NodeManager::ReservedNodes` (`max_values`: None, `max_size`: Some(112), added: 2587, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::TotalReservedNodes` (r:1 w:1)
	/// Proof: `NodeManager::TotalReservedNodes` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::TotalRegisteredNodes` (r:1 w:1)
	/// Proof: `NodeManager::TotalRegisteredNodes` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::OwnedNodesCount` (r:1 w:1)
	/// Proof: `NodeManager::OwnedNodesCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::NextNodeSerialNumber` (r:1 w:1)
	/// Proof: `NodeManager::NextNodeSerialNumber` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::RewardPeriod` (r:1 w:0)
	/// Proof: `NodeManager::RewardPeriod` (`max_values`: Some(1), `max_size`: Some(24), added: 519, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::TotalUptime` (r:1 w:1)
	/// Proof: `NodeManager::TotalUptime` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::OwnedNodes` (r:0 w:1)
	/// Proof: `NodeManager::OwnedNodes` (`max_values`: None, `max_size`: Some(96), added: 2571, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::NodeUptime` (r:0 w:1)
	/// Proof: `NodeManager::NodeUptime` (`max_values`: None, `max_size`: Some(100), added: 2575, mode: `MaxEncodedLen`)
	fn register_reserved_node() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `392`
		//  Estimated: `3581`
		// Minimum execution time: 75_402_000 picoseconds.
		Weight::from_parts(76_902_000, 3581)
			.saturating_add(T::DbWeight::get().reads(10_u64))
			.saturating_add(T::DbWeight::get().writes(10_u64))
	}
	/// Storage: `NodeManager::NodeRegistrar` (r:1 w:1)
	/// Proof: `NodeManager::NodeRegistrar` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	fn set_admin_config_registrar() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `221`
		//  Estimated: `1517`
		// Minimum execution time: 21_800_000 picoseconds.
		Weight::from_parts(22_291_000, 1517)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `NodeManager::NextHeartbeatPeriod` (r:1 w:0)
	/// Proof: `NodeManager::NextHeartbeatPeriod` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::RewardPeriod` (r:1 w:0)
	/// Proof: `NodeManager::RewardPeriod` (`max_values`: Some(1), `max_size`: Some(24), added: 519, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::NextRewardPeriodLength` (r:1 w:1)
	/// Proof: `NodeManager::NextRewardPeriodLength` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn set_admin_config_reward_period() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `180`
		//  Estimated: `1509`
		// Minimum execution time: 23_951_000 picoseconds.
		Weight::from_parts(24_361_000, 1509)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `NodeManager::MaxBatchSize` (r:1 w:1)
	/// Proof: `NodeManager::MaxBatchSize` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn set_admin_config_reward_batch_size() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `169`
		//  Estimated: `1489`
		// Minimum execution time: 17_890_000 picoseconds.
		Weight::from_parts(18_550_000, 1489)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `NodeManager::NextRewardPeriodLength` (r:1 w:0)
	/// Proof: `NodeManager::NextRewardPeriodLength` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::NextHeartbeatPeriod` (r:0 w:1)
	/// Proof: `NodeManager::NextHeartbeatPeriod` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn set_admin_config_reward_heartbeat() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `169`
		//  Estimated: `1489`
		// Minimum execution time: 17_740_000 picoseconds.
		Weight::from_parts(18_290_000, 1489)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `NodeManager::RewardPot` (r:1 w:1)
	/// Proof: `NodeManager::RewardPot` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::OutstandingRewardToPay` (r:1 w:1)
	/// Proof: `NodeManager::OutstandingRewardToPay` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::TotalLockedRewards` (r:1 w:0)
	/// Proof: `NodeManager::TotalLockedRewards` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:0)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn set_reward_amount() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `393`
		//  Estimated: `3593`
		// Minimum execution time: 74_402_000 picoseconds.
		Weight::from_parts(76_482_000, 3593)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `NodeManager::RewardEnabled` (r:0 w:1)
	/// Proof: `NodeManager::RewardEnabled` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	fn set_admin_config_reward_enabled() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 10_691_000 picoseconds.
		Weight::from_parts(11_620_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `NodeManager::MinUptimeThreshold` (r:0 w:1)
	/// Proof: `NodeManager::MinUptimeThreshold` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn set_admin_config_min_threshold() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 10_441_000 picoseconds.
		Weight::from_parts(10_870_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `NodeManager::RewardEnabled` (r:1 w:0)
	/// Proof: `NodeManager::RewardEnabled` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::RewardPeriod` (r:1 w:1)
	/// Proof: `NodeManager::RewardPeriod` (`max_values`: Some(1), `max_size`: Some(24), added: 519, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::NextRewardPeriodLength` (r:1 w:0)
	/// Proof: `NodeManager::NextRewardPeriodLength` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::NextHeartbeatPeriod` (r:1 w:0)
	/// Proof: `NodeManager::NextHeartbeatPeriod` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::MinUptimeThreshold` (r:1 w:0)
	/// Proof: `NodeManager::MinUptimeThreshold` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::RewardPot` (r:0 w:1)
	/// Proof: `NodeManager::RewardPot` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `MaxEncodedLen`)
	fn on_initialise_with_new_reward_period() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `294`
		//  Estimated: `1509`
		// Minimum execution time: 33_451_000 picoseconds.
		Weight::from_parts(33_951_000, 1509)
			.saturating_add(T::DbWeight::get().reads(6_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `NodeManager::RewardEnabled` (r:1 w:0)
	/// Proof: `NodeManager::RewardEnabled` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::RewardPeriod` (r:1 w:0)
	/// Proof: `NodeManager::RewardPeriod` (`max_values`: Some(1), `max_size`: Some(24), added: 519, mode: `MaxEncodedLen`)
	fn on_initialise_no_reward_period() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `200`
		//  Estimated: `1509`
		// Minimum execution time: 12_890_000 picoseconds.
		Weight::from_parts(13_411_000, 1509)
			.saturating_add(T::DbWeight::get().reads(2_u64))
	}
	/// Storage: `NodeManager::NodeRegistry` (r:1 w:0)
	/// Proof: `NodeManager::NodeRegistry` (`max_values`: None, `max_size`: Some(116), added: 2591, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::RewardPeriod` (r:1 w:0)
	/// Proof: `NodeManager::RewardPeriod` (`max_values`: Some(1), `max_size`: Some(24), added: 519, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::NodeUptime` (r:1 w:1)
	/// Proof: `NodeManager::NodeUptime` (`max_values`: None, `max_size`: Some(100), added: 2575, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::TotalUptime` (r:1 w:1)
	/// Proof: `NodeManager::TotalUptime` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	fn offchain_submit_heartbeat() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `582`
		//  Estimated: `3581`
		// Minimum execution time: 56_031_000 picoseconds.
		Weight::from_parts(56_671_000, 3581)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `NodeManager::NodeRegistry` (r:1024 w:0)
	/// Proof: `NodeManager::NodeRegistry` (`max_values`: None, `max_size`: Some(116), added: 2591, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::RewardPeriod` (r:1 w:0)
	/// Proof: `NodeManager::RewardPeriod` (`max_values`: Some(1), `max_size`: Some(24), added: 519, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::NodeUptime` (r:1023 w:1023)
	/// Proof: `NodeManager::NodeUptime` (`max_values`: None, `max_size`: Some(100), added: 2575, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::TotalUptime` (r:1 w:1)
	/// Proof: `NodeManager::TotalUptime` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// The range of component `b` is `[1, 1024]`.
	fn heartbeat_for_owned_nodes(b: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `576 + b * (207 ±0)`
		//  Estimated: `3581 + b * (2591 ±0)`
		// Minimum execution time: 165_984_000 picoseconds.
		Weight::from_parts(167_465_000, 3581)
			// Standard Error: 35_932
			.saturating_add(Weight::from_parts(27_352_387, 0).saturating_mul(b.into()))
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().reads((2_u64).saturating_mul(b.into())))
			.saturating_add(T::DbWeight::get().writes(1_u64))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(b.into())))
			.saturating_add(Weight::from_parts(0, 2591).saturating_mul(b.into()))
	}
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn top_up_reward_pot() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `243`
		//  Estimated: `6196`
		// Minimum execution time: 78_333_000 picoseconds.
		Weight::from_parts(79_442_000, 6196)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `NodeManager::NodeRegistrar` (r:1 w:0)
	/// Proof: `NodeManager::NodeRegistrar` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::RewardPeriod` (r:1 w:0)
	/// Proof: `NodeManager::RewardPeriod` (`max_values`: Some(1), `max_size`: Some(24), added: 519, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::OldestUnpaidRewardPeriodIndex` (r:1 w:0)
	/// Proof: `NodeManager::OldestUnpaidRewardPeriodIndex` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::OwnedNodes` (r:64 w:64)
	/// Proof: `NodeManager::OwnedNodes` (`max_values`: None, `max_size`: Some(96), added: 2571, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::NodeRegistry` (r:64 w:64)
	/// Proof: `NodeManager::NodeRegistry` (`max_values`: None, `max_size`: Some(116), added: 2591, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::SigningKeyToNodeId` (r:64 w:0)
	/// Proof: `NodeManager::SigningKeyToNodeId` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::OwnedNodesCount` (r:1 w:1)
	/// Proof: `NodeManager::OwnedNodesCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::TotalRegisteredNodes` (r:1 w:1)
	/// Proof: `NodeManager::TotalRegisteredNodes` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::NodeUptime` (r:64 w:64)
	/// Proof: `NodeManager::NodeUptime` (`max_values`: None, `max_size`: Some(100), added: 2575, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::TotalUptime` (r:1 w:1)
	/// Proof: `NodeManager::TotalUptime` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// The range of component `b` is `[1, 64]`.
	fn deregister_nodes(b: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `541 + b * (262 ±0)`
		//  Estimated: `3517 + b * (2591 ±0)`
		// Minimum execution time: 79_332_000 picoseconds.
		Weight::from_parts(51_626_682, 3517)
			// Standard Error: 41_491
			.saturating_add(Weight::from_parts(36_370_279, 0).saturating_mul(b.into()))
			.saturating_add(T::DbWeight::get().reads(6_u64))
			.saturating_add(T::DbWeight::get().reads((4_u64).saturating_mul(b.into())))
			.saturating_add(T::DbWeight::get().writes(3_u64))
			.saturating_add(T::DbWeight::get().writes((3_u64).saturating_mul(b.into())))
			.saturating_add(Weight::from_parts(0, 2591).saturating_mul(b.into()))
	}
	/// Storage: `NodeManager::NodeRegistrar` (r:1 w:0)
	/// Proof: `NodeManager::NodeRegistrar` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::NodeRegistry` (r:1 w:1)
	/// Proof: `NodeManager::NodeRegistry` (`max_values`: None, `max_size`: Some(116), added: 2591, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::SigningKeyToNodeId` (r:2 w:1)
	/// Proof: `NodeManager::SigningKeyToNodeId` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	fn update_signing_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `425`
		//  Estimated: `6100`
		// Minimum execution time: 46_272_000 picoseconds.
		Weight::from_parts(47_091_000, 6100)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `NodeManager::NodeUptime` (r:2 w:1)
	/// Proof: `NodeManager::NodeUptime` (`max_values`: None, `max_size`: Some(100), added: 2575, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::NodeRegistry` (r:1 w:0)
	/// Proof: `NodeManager::NodeRegistry` (`max_values`: None, `max_size`: Some(116), added: 2591, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::LockSchedule` (r:1 w:0)
	/// Proof: `NodeManager::LockSchedule` (`max_values`: Some(1), `max_size`: Some(12), added: 507, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn pay_one_node() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `816`
		//  Estimated: `6196`
		// Minimum execution time: 118_083_000 picoseconds.
		Weight::from_parts(118_763_000, 6196)
			.saturating_add(T::DbWeight::get().reads(7_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `NodeManager::MaxBatchSize` (r:1 w:0)
	/// Proof: `NodeManager::MaxBatchSize` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::RewardPeriod` (r:1 w:0)
	/// Proof: `NodeManager::RewardPeriod` (`max_values`: Some(1), `max_size`: Some(24), added: 519, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::OldestUnpaidRewardPeriodIndex` (r:1 w:1)
	/// Proof: `NodeManager::OldestUnpaidRewardPeriodIndex` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::RewardPot` (r:1 w:1)
	/// Proof: `NodeManager::RewardPot` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::TotalUptime` (r:1 w:1)
	/// Proof: `NodeManager::TotalUptime` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::NodeUptime` (r:1 w:0)
	/// Proof: `NodeManager::NodeUptime` (`max_values`: None, `max_size`: Some(100), added: 2575, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::OutstandingRewardToPay` (r:1 w:1)
	/// Proof: `NodeManager::OutstandingRewardToPay` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn complete_reward_period() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `658`
		//  Estimated: `6196`
		// Minimum execution time: 125_263_000 picoseconds.
		Weight::from_parts(126_244_000, 6196)
			.saturating_add(T::DbWeight::get().reads(10_u64))
			.saturating_add(T::DbWeight::get().writes(6_u64))
	}
	/// Storage: `NodeManager::LockSchedule` (r:0 w:1)
	/// Proof: `NodeManager::LockSchedule` (`max_values`: Some(1), `max_size`: Some(12), added: 507, mode: `MaxEncodedLen`)
	fn set_admin_config_lock_schedule() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 10_800_000 picoseconds.
		Weight::from_parts(11_060_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `NodeManager::ForfeitureDestination` (r:0 w:1)
	/// Proof: `NodeManager::ForfeitureDestination` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	fn set_admin_config_forfeiture_destination() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 10_830_000 picoseconds.
		Weight::from_parts(11_180_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `NodeManager::NodeRegistry` (r:64 w:0)
	/// Proof: `NodeManager::NodeRegistry` (`max_values`: None, `max_size`: Some(116), added: 2591, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::ReservedNodes` (r:64 w:64)
	/// Proof: `NodeManager::ReservedNodes` (`max_values`: None, `max_size`: Some(112), added: 2587, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::TotalRegisteredNodes` (r:1 w:0)
	/// Proof: `NodeManager::TotalRegisteredNodes` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::TotalReservedNodes` (r:1 w:1)
	/// Proof: `NodeManager::TotalReservedNodes` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// The range of component `b` is `[1, 64]`.
	fn set_admin_config_reserve_nodes(b: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `169`
		//  Estimated: `1489 + b * (2591 ±0)`
		// Minimum execution time: 32_051_000 picoseconds.
		Weight::from_parts(20_732_195, 1489)
			// Standard Error: 15_782
			.saturating_add(Weight::from_parts(8_074_984, 0).saturating_mul(b.into()))
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().reads((2_u64).saturating_mul(b.into())))
			.saturating_add(T::DbWeight::get().writes(1_u64))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(b.into())))
			.saturating_add(Weight::from_parts(0, 2591).saturating_mul(b.into()))
	}
	/// Storage: `NodeManager::LockedRewards` (r:1 w:1)
	/// Proof: `NodeManager::LockedRewards` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::LockSchedule` (r:1 w:0)
	/// Proof: `NodeManager::LockSchedule` (`max_values`: Some(1), `max_size`: Some(12), added: 507, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:3 w:3)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::ForfeitureDestination` (r:1 w:0)
	/// Proof: `NodeManager::ForfeitureDestination` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::TotalLockedRewards` (r:1 w:1)
	/// Proof: `NodeManager::TotalLockedRewards` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	fn withdraw_rewards() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `793`
		//  Estimated: `8799`
		// Minimum execution time: 180_275_000 picoseconds.
		Weight::from_parts(182_095_000, 8799)
			.saturating_add(T::DbWeight::get().reads(8_u64))
			.saturating_add(T::DbWeight::get().writes(5_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `NodeManager::NodeRegistrar` (r:1 w:0)
	/// Proof: `NodeManager::NodeRegistrar` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::NodeRegistry` (r:1 w:1)
	/// Proof: `NodeManager::NodeRegistry` (`max_values`: None, `max_size`: Some(116), added: 2591, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::SigningKeyToNodeId` (r:1 w:1)
	/// Proof: `NodeManager::SigningKeyToNodeId` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::ReservedNodes` (r:1 w:0)
	/// Proof: `NodeManager::ReservedNodes` (`max_values`: None, `max_size`: Some(112), added: 2587, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::TotalRegisteredNodes` (r:1 w:1)
	/// Proof: `NodeManager::TotalRegisteredNodes` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::TotalReservedNodes` (r:1 w:0)
	/// Proof: `NodeManager::TotalReservedNodes` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::OwnedNodesCount` (r:1 w:1)
	/// Proof: `NodeManager::OwnedNodesCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::NextNodeSerialNumber` (r:1 w:1)
	/// Proof: `NodeManager::NextNodeSerialNumber` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::OwnedNodes` (r:0 w:1)
	/// Proof: `NodeManager::OwnedNodes` (`max_values`: None, `max_size`: Some(96), added: 2571, mode: `MaxEncodedLen`)
	fn register_node() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `221`
		//  Estimated: `3581`
		// Minimum execution time: 53_072_000 picoseconds.
		Weight::from_parts(54_131_000, 3581)
			.saturating_add(RocksDbWeight::get().reads(8_u64))
			.saturating_add(RocksDbWeight::get().writes(6_u64))
	}
	/// Storage: `NodeManager::NodeRegistrar` (r:1 w:0)
	/// Proof: `NodeManager::NodeRegistrar` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::NodeRegistry` (r:1 w:1)
	/// Proof: `NodeManager::NodeRegistry` (`max_values`: None, `max_size`: Some(116), added: 2591, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::SigningKeyToNodeId` (r:1 w:1)
	/// Proof: `NodeManager::SigningKeyToNodeId` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::ReservedNodes` (r:1 w:1)
	/// Proof: `NodeManager::ReservedNodes` (`max_values`: None, `max_size`: Some(112), added: 2587, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::TotalReservedNodes` (r:1 w:1)
	/// Proof: `NodeManager::TotalReservedNodes` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::TotalRegisteredNodes` (r:1 w:1)
	/// Proof: `NodeManager::TotalRegisteredNodes` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::OwnedNodesCount` (r:1 w:1)
	/// Proof: `NodeManager::OwnedNodesCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::NextNodeSerialNumber` (r:1 w:1)
	/// Proof: `NodeManager::NextNodeSerialNumber` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::RewardPeriod` (r:1 w:0)
	/// Proof: `NodeManager::RewardPeriod` (`max_values`: Some(1), `max_size`: Some(24), added: 519, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::TotalUptime` (r:1 w:1)
	/// Proof: `NodeManager::TotalUptime` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::OwnedNodes` (r:0 w:1)
	/// Proof: `NodeManager::OwnedNodes` (`max_values`: None, `max_size`: Some(96), added: 2571, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::NodeUptime` (r:0 w:1)
	/// Proof: `NodeManager::NodeUptime` (`max_values`: None, `max_size`: Some(100), added: 2575, mode: `MaxEncodedLen`)
	fn register_reserved_node() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `392`
		//  Estimated: `3581`
		// Minimum execution time: 75_402_000 picoseconds.
		Weight::from_parts(76_902_000, 3581)
			.saturating_add(RocksDbWeight::get().reads(10_u64))
			.saturating_add(RocksDbWeight::get().writes(10_u64))
	}
	/// Storage: `NodeManager::NodeRegistrar` (r:1 w:1)
	/// Proof: `NodeManager::NodeRegistrar` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	fn set_admin_config_registrar() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `221`
		//  Estimated: `1517`
		// Minimum execution time: 21_800_000 picoseconds.
		Weight::from_parts(22_291_000, 1517)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `NodeManager::NextHeartbeatPeriod` (r:1 w:0)
	/// Proof: `NodeManager::NextHeartbeatPeriod` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::RewardPeriod` (r:1 w:0)
	/// Proof: `NodeManager::RewardPeriod` (`max_values`: Some(1), `max_size`: Some(24), added: 519, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::NextRewardPeriodLength` (r:1 w:1)
	/// Proof: `NodeManager::NextRewardPeriodLength` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn set_admin_config_reward_period() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `180`
		//  Estimated: `1509`
		// Minimum execution time: 23_951_000 picoseconds.
		Weight::from_parts(24_361_000, 1509)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `NodeManager::MaxBatchSize` (r:1 w:1)
	/// Proof: `NodeManager::MaxBatchSize` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn set_admin_config_reward_batch_size() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `169`
		//  Estimated: `1489`
		// Minimum execution time: 17_890_000 picoseconds.
		Weight::from_parts(18_550_000, 1489)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `NodeManager::NextRewardPeriodLength` (r:1 w:0)
	/// Proof: `NodeManager::NextRewardPeriodLength` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::NextHeartbeatPeriod` (r:0 w:1)
	/// Proof: `NodeManager::NextHeartbeatPeriod` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn set_admin_config_reward_heartbeat() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `169`
		//  Estimated: `1489`
		// Minimum execution time: 17_740_000 picoseconds.
		Weight::from_parts(18_290_000, 1489)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `NodeManager::RewardPot` (r:1 w:1)
	/// Proof: `NodeManager::RewardPot` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::OutstandingRewardToPay` (r:1 w:1)
	/// Proof: `NodeManager::OutstandingRewardToPay` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::TotalLockedRewards` (r:1 w:0)
	/// Proof: `NodeManager::TotalLockedRewards` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:0)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn set_reward_amount() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `393`
		//  Estimated: `3593`
		// Minimum execution time: 74_402_000 picoseconds.
		Weight::from_parts(76_482_000, 3593)
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `NodeManager::RewardEnabled` (r:0 w:1)
	/// Proof: `NodeManager::RewardEnabled` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	fn set_admin_config_reward_enabled() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 10_691_000 picoseconds.
		Weight::from_parts(11_620_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `NodeManager::MinUptimeThreshold` (r:0 w:1)
	/// Proof: `NodeManager::MinUptimeThreshold` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn set_admin_config_min_threshold() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 10_441_000 picoseconds.
		Weight::from_parts(10_870_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `NodeManager::RewardEnabled` (r:1 w:0)
	/// Proof: `NodeManager::RewardEnabled` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::RewardPeriod` (r:1 w:1)
	/// Proof: `NodeManager::RewardPeriod` (`max_values`: Some(1), `max_size`: Some(24), added: 519, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::NextRewardPeriodLength` (r:1 w:0)
	/// Proof: `NodeManager::NextRewardPeriodLength` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::NextHeartbeatPeriod` (r:1 w:0)
	/// Proof: `NodeManager::NextHeartbeatPeriod` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::MinUptimeThreshold` (r:1 w:0)
	/// Proof: `NodeManager::MinUptimeThreshold` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::RewardPot` (r:0 w:1)
	/// Proof: `NodeManager::RewardPot` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `MaxEncodedLen`)
	fn on_initialise_with_new_reward_period() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `294`
		//  Estimated: `1509`
		// Minimum execution time: 33_451_000 picoseconds.
		Weight::from_parts(33_951_000, 1509)
			.saturating_add(RocksDbWeight::get().reads(6_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `NodeManager::RewardEnabled` (r:1 w:0)
	/// Proof: `NodeManager::RewardEnabled` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::RewardPeriod` (r:1 w:0)
	/// Proof: `NodeManager::RewardPeriod` (`max_values`: Some(1), `max_size`: Some(24), added: 519, mode: `MaxEncodedLen`)
	fn on_initialise_no_reward_period() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `200`
		//  Estimated: `1509`
		// Minimum execution time: 12_890_000 picoseconds.
		Weight::from_parts(13_411_000, 1509)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
	}
	/// Storage: `NodeManager::NodeRegistry` (r:1 w:0)
	/// Proof: `NodeManager::NodeRegistry` (`max_values`: None, `max_size`: Some(116), added: 2591, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::RewardPeriod` (r:1 w:0)
	/// Proof: `NodeManager::RewardPeriod` (`max_values`: Some(1), `max_size`: Some(24), added: 519, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::NodeUptime` (r:1 w:1)
	/// Proof: `NodeManager::NodeUptime` (`max_values`: None, `max_size`: Some(100), added: 2575, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::TotalUptime` (r:1 w:1)
	/// Proof: `NodeManager::TotalUptime` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	fn offchain_submit_heartbeat() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `582`
		//  Estimated: `3581`
		// Minimum execution time: 56_031_000 picoseconds.
		Weight::from_parts(56_671_000, 3581)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `NodeManager::NodeRegistry` (r:1024 w:0)
	/// Proof: `NodeManager::NodeRegistry` (`max_values`: None, `max_size`: Some(116), added: 2591, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::RewardPeriod` (r:1 w:0)
	/// Proof: `NodeManager::RewardPeriod` (`max_values`: Some(1), `max_size`: Some(24), added: 519, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::NodeUptime` (r:1023 w:1023)
	/// Proof: `NodeManager::NodeUptime` (`max_values`: None, `max_size`: Some(100), added: 2575, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::TotalUptime` (r:1 w:1)
	/// Proof: `NodeManager::TotalUptime` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// The range of component `b` is `[1, 1024]`.
	fn heartbeat_for_owned_nodes(b: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `576 + b * (207 ±0)`
		//  Estimated: `3581 + b * (2591 ±0)`
		// Minimum execution time: 165_984_000 picoseconds.
		Weight::from_parts(167_465_000, 3581)
			// Standard Error: 35_932
			.saturating_add(Weight::from_parts(27_352_387, 0).saturating_mul(b.into()))
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().reads((2_u64).saturating_mul(b.into())))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
			.saturating_add(RocksDbWeight::get().writes((1_u64).saturating_mul(b.into())))
			.saturating_add(Weight::from_parts(0, 2591).saturating_mul(b.into()))
	}
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn top_up_reward_pot() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `243`
		//  Estimated: `6196`
		// Minimum execution time: 78_333_000 picoseconds.
		Weight::from_parts(79_442_000, 6196)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `NodeManager::NodeRegistrar` (r:1 w:0)
	/// Proof: `NodeManager::NodeRegistrar` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::RewardPeriod` (r:1 w:0)
	/// Proof: `NodeManager::RewardPeriod` (`max_values`: Some(1), `max_size`: Some(24), added: 519, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::OldestUnpaidRewardPeriodIndex` (r:1 w:0)
	/// Proof: `NodeManager::OldestUnpaidRewardPeriodIndex` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::OwnedNodes` (r:64 w:64)
	/// Proof: `NodeManager::OwnedNodes` (`max_values`: None, `max_size`: Some(96), added: 2571, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::NodeRegistry` (r:64 w:64)
	/// Proof: `NodeManager::NodeRegistry` (`max_values`: None, `max_size`: Some(116), added: 2591, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::SigningKeyToNodeId` (r:64 w:0)
	/// Proof: `NodeManager::SigningKeyToNodeId` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::OwnedNodesCount` (r:1 w:1)
	/// Proof: `NodeManager::OwnedNodesCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::TotalRegisteredNodes` (r:1 w:1)
	/// Proof: `NodeManager::TotalRegisteredNodes` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::NodeUptime` (r:64 w:64)
	/// Proof: `NodeManager::NodeUptime` (`max_values`: None, `max_size`: Some(100), added: 2575, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::TotalUptime` (r:1 w:1)
	/// Proof: `NodeManager::TotalUptime` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// The range of component `b` is `[1, 64]`.
	fn deregister_nodes(b: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `541 + b * (262 ±0)`
		//  Estimated: `3517 + b * (2591 ±0)`
		// Minimum execution time: 79_332_000 picoseconds.
		Weight::from_parts(51_626_682, 3517)
			// Standard Error: 41_491
			.saturating_add(Weight::from_parts(36_370_279, 0).saturating_mul(b.into()))
			.saturating_add(RocksDbWeight::get().reads(6_u64))
			.saturating_add(RocksDbWeight::get().reads((4_u64).saturating_mul(b.into())))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
			.saturating_add(RocksDbWeight::get().writes((3_u64).saturating_mul(b.into())))
			.saturating_add(Weight::from_parts(0, 2591).saturating_mul(b.into()))
	}
	/// Storage: `NodeManager::NodeRegistrar` (r:1 w:0)
	/// Proof: `NodeManager::NodeRegistrar` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::NodeRegistry` (r:1 w:1)
	/// Proof: `NodeManager::NodeRegistry` (`max_values`: None, `max_size`: Some(116), added: 2591, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::SigningKeyToNodeId` (r:2 w:1)
	/// Proof: `NodeManager::SigningKeyToNodeId` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	fn update_signing_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `425`
		//  Estimated: `6100`
		// Minimum execution time: 46_272_000 picoseconds.
		Weight::from_parts(47_091_000, 6100)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `NodeManager::NodeUptime` (r:2 w:1)
	/// Proof: `NodeManager::NodeUptime` (`max_values`: None, `max_size`: Some(100), added: 2575, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::NodeRegistry` (r:1 w:0)
	/// Proof: `NodeManager::NodeRegistry` (`max_values`: None, `max_size`: Some(116), added: 2591, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::LockSchedule` (r:1 w:0)
	/// Proof: `NodeManager::LockSchedule` (`max_values`: Some(1), `max_size`: Some(12), added: 507, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn pay_one_node() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `816`
		//  Estimated: `6196`
		// Minimum execution time: 118_083_000 picoseconds.
		Weight::from_parts(118_763_000, 6196)
			.saturating_add(RocksDbWeight::get().reads(7_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `NodeManager::MaxBatchSize` (r:1 w:0)
	/// Proof: `NodeManager::MaxBatchSize` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::RewardPeriod` (r:1 w:0)
	/// Proof: `NodeManager::RewardPeriod` (`max_values`: Some(1), `max_size`: Some(24), added: 519, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::OldestUnpaidRewardPeriodIndex` (r:1 w:1)
	/// Proof: `NodeManager::OldestUnpaidRewardPeriodIndex` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::RewardPot` (r:1 w:1)
	/// Proof: `NodeManager::RewardPot` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::TotalUptime` (r:1 w:1)
	/// Proof: `NodeManager::TotalUptime` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::NodeUptime` (r:1 w:0)
	/// Proof: `NodeManager::NodeUptime` (`max_values`: None, `max_size`: Some(100), added: 2575, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::OutstandingRewardToPay` (r:1 w:1)
	/// Proof: `NodeManager::OutstandingRewardToPay` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn complete_reward_period() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `658`
		//  Estimated: `6196`
		// Minimum execution time: 125_263_000 picoseconds.
		Weight::from_parts(126_244_000, 6196)
			.saturating_add(RocksDbWeight::get().reads(10_u64))
			.saturating_add(RocksDbWeight::get().writes(6_u64))
	}
	/// Storage: `NodeManager::LockSchedule` (r:0 w:1)
	/// Proof: `NodeManager::LockSchedule` (`max_values`: Some(1), `max_size`: Some(12), added: 507, mode: `MaxEncodedLen`)
	fn set_admin_config_lock_schedule() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 10_800_000 picoseconds.
		Weight::from_parts(11_060_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `NodeManager::ForfeitureDestination` (r:0 w:1)
	/// Proof: `NodeManager::ForfeitureDestination` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	fn set_admin_config_forfeiture_destination() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 10_830_000 picoseconds.
		Weight::from_parts(11_180_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `NodeManager::NodeRegistry` (r:64 w:0)
	/// Proof: `NodeManager::NodeRegistry` (`max_values`: None, `max_size`: Some(116), added: 2591, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::ReservedNodes` (r:64 w:64)
	/// Proof: `NodeManager::ReservedNodes` (`max_values`: None, `max_size`: Some(112), added: 2587, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::TotalRegisteredNodes` (r:1 w:0)
	/// Proof: `NodeManager::TotalRegisteredNodes` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::TotalReservedNodes` (r:1 w:1)
	/// Proof: `NodeManager::TotalReservedNodes` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// The range of component `b` is `[1, 64]`.
	fn set_admin_config_reserve_nodes(b: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `169`
		//  Estimated: `1489 + b * (2591 ±0)`
		// Minimum execution time: 32_051_000 picoseconds.
		Weight::from_parts(20_732_195, 1489)
			// Standard Error: 15_782
			.saturating_add(Weight::from_parts(8_074_984, 0).saturating_mul(b.into()))
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().reads((2_u64).saturating_mul(b.into())))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
			.saturating_add(RocksDbWeight::get().writes((1_u64).saturating_mul(b.into())))
			.saturating_add(Weight::from_parts(0, 2591).saturating_mul(b.into()))
	}
	/// Storage: `NodeManager::LockedRewards` (r:1 w:1)
	/// Proof: `NodeManager::LockedRewards` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::LockSchedule` (r:1 w:0)
	/// Proof: `NodeManager::LockSchedule` (`max_values`: Some(1), `max_size`: Some(12), added: 507, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:3 w:3)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::ForfeitureDestination` (r:1 w:0)
	/// Proof: `NodeManager::ForfeitureDestination` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::TotalLockedRewards` (r:1 w:1)
	/// Proof: `NodeManager::TotalLockedRewards` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	fn withdraw_rewards() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `793`
		//  Estimated: `8799`
		// Minimum execution time: 180_275_000 picoseconds.
		Weight::from_parts(182_095_000, 8799)
			.saturating_add(RocksDbWeight::get().reads(8_u64))
			.saturating_add(RocksDbWeight::get().writes(5_u64))
	}
}
