//! Autogenerated weights for pallet_node_manager
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 48.0.0
//! DATE: 2026-04-11, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `ip-172-31-1-153`, CPU: `AMD EPYC 7R32`
//! EXECUTION: ``, WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// ./avn-parachain-collator
// benchmark
// pallet
// --chain
// dev
// --wasm-execution=compiled
// --template
// frame-weight-template.hbs
// --pallet
// pallet_node_manager
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --output
// node_manager_weights2.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for pallet_node_manager.
pub trait WeightInfo {
	fn register_node() -> Weight;
	fn set_admin_config_registrar() -> Weight;
	fn set_admin_config_reward_period() -> Weight;
	fn set_admin_config_reward_batch_size() -> Weight;
	fn set_admin_config_reward_heartbeat() -> Weight;
	fn set_admin_config_reward_amount() -> Weight;
	fn set_admin_config_reward_enabled() -> Weight;
	fn set_admin_config_min_threshold() -> Weight;
	fn on_initialise_with_new_reward_period() -> Weight;
	fn on_initialise_no_reward_period() -> Weight;
	fn offchain_submit_heartbeat() -> Weight;
	fn signed_register_node() -> Weight;
	fn deregister_nodes(b: u32, ) -> Weight;
	fn signed_deregister_nodes(b: u32, ) -> Weight;
	fn update_signing_key() -> Weight;
	fn top_up_reward_pot() -> Weight;
	fn set_halving_enabled() -> Weight;
	fn heartbeat_for_owned_nodes(b: u32, ) -> Weight;
	fn set_admin_config_lock_schedule() -> Weight;
	fn set_admin_config_forfeiture_destination() -> Weight;
	fn withdraw_rewards() -> Weight;
}

/// Weights for pallet_node_manager using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `NodeManager::NodeRegistrar` (r:1 w:0)
	/// Proof: `NodeManager::NodeRegistrar` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::NodeRegistry` (r:1 w:1)
	/// Proof: `NodeManager::NodeRegistry` (`max_values`: None, `max_size`: Some(191), added: 2666, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::SigningKeyToNodeId` (r:1 w:1)
	/// Proof: `NodeManager::SigningKeyToNodeId` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::NextNodeSerialNumber` (r:1 w:1)
	/// Proof: `NodeManager::NextNodeSerialNumber` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::AutoStakeDurationSec` (r:1 w:0)
	/// Proof: `NodeManager::AutoStakeDurationSec` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::OwnedNodesCount` (r:1 w:1)
	/// Proof: `NodeManager::OwnedNodesCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::TotalRegisteredNodes` (r:1 w:1)
	/// Proof: `NodeManager::TotalRegisteredNodes` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::OwnedNodes` (r:0 w:1)
	/// Proof: `NodeManager::OwnedNodes` (`max_values`: None, `max_size`: Some(96), added: 2571, mode: `MaxEncodedLen`)
	fn register_node() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `433`
		//  Estimated: `3656`
		// Minimum execution time: 67_881_000 picoseconds.
		Weight::from_parts(84_332_000, 3656)
			.saturating_add(T::DbWeight::get().reads(8_u64))
			.saturating_add(T::DbWeight::get().writes(6_u64))
	}
	/// Storage: `NodeManager::NodeRegistrar` (r:1 w:0)
	/// Proof: `NodeManager::NodeRegistrar` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::NodeRegistry` (r:1 w:1)
	/// Proof: `NodeManager::NodeRegistry` (`max_values`: None, `max_size`: Some(191), added: 2666, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::SigningKeyToNodeId` (r:1 w:1)
	/// Proof: `NodeManager::SigningKeyToNodeId` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::AutoStakeDurationSec` (r:1 w:0)
	/// Proof: `NodeManager::AutoStakeDurationSec` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::OwnedNodesCount` (r:1 w:1)
	/// Proof: `NodeManager::OwnedNodesCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::TotalRegisteredNodes` (r:1 w:1)
	/// Proof: `NodeManager::TotalRegisteredNodes` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::NodeRegistrar` (r:1 w:1)
	/// Proof: `NodeManager::NodeRegistrar` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	fn set_admin_config_registrar() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `360`
		//  Estimated: `1517`
		// Minimum execution time: 19_011_000 picoseconds.
		Weight::from_parts(19_331_000, 1517)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `NodeManager::NextHeartbeatPeriod` (r:1 w:0)
	/// Proof: `NodeManager::NextHeartbeatPeriod` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::RewardPeriod` (r:1 w:0)
	/// Proof: `NodeManager::RewardPeriod` (`max_values`: Some(1), `max_size`: Some(40), added: 535, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::NextRewardPeriodLength` (r:1 w:1)
	/// Proof: `NodeManager::NextRewardPeriodLength` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn set_admin_config_reward_period() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `383`
		//  Estimated: `1525`
		// Minimum execution time: 24_981_000 picoseconds.
		Weight::from_parts(25_611_000, 1525)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `NodeManager::MaxBatchSize` (r:1 w:1)
	/// Proof: `NodeManager::MaxBatchSize` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn set_admin_config_reward_batch_size() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `308`
		//  Estimated: `1489`
		// Minimum execution time: 17_240_000 picoseconds.
		Weight::from_parts(17_821_000, 1489)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `NodeManager::NextRewardPeriodLength` (r:1 w:0)
	/// Proof: `NodeManager::NextRewardPeriodLength` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::NextHeartbeatPeriod` (r:0 w:1)
	/// Proof: `NodeManager::NextHeartbeatPeriod` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn set_admin_config_reward_heartbeat() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `308`
		//  Estimated: `1489`
		// Minimum execution time: 17_410_000 picoseconds.
		Weight::from_parts(17_971_000, 1489)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `NodeManager::NextRewardAmountPerPeriod` (r:0 w:1)
	/// Proof: `NodeManager::NextRewardAmountPerPeriod` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	fn set_admin_config_reward_amount() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 10_070_000 picoseconds.
		Weight::from_parts(10_410_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `NodeManager::RewardEnabled` (r:0 w:1)
	/// Proof: `NodeManager::RewardEnabled` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	fn set_admin_config_reward_enabled() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 10_170_000 picoseconds.
		Weight::from_parts(10_621_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `NodeManager::MinUptimeThreshold` (r:0 w:1)
	/// Proof: `NodeManager::MinUptimeThreshold` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn set_admin_config_min_threshold() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 10_101_000 picoseconds.
		Weight::from_parts(10_830_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `NodeManager::RewardEnabled` (r:1 w:0)
	/// Proof: `NodeManager::RewardEnabled` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::RewardPeriod` (r:1 w:1)
	/// Proof: `NodeManager::RewardPeriod` (`max_values`: Some(1), `max_size`: Some(40), added: 535, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::NextRewardPeriodLength` (r:1 w:0)
	/// Proof: `NodeManager::NextRewardPeriodLength` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::NextHeartbeatPeriod` (r:1 w:0)
	/// Proof: `NodeManager::NextHeartbeatPeriod` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::NextRewardAmountPerPeriod` (r:1 w:0)
	/// Proof: `NodeManager::NextRewardAmountPerPeriod` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::MinUptimeThreshold` (r:1 w:0)
	/// Proof: `NodeManager::MinUptimeThreshold` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::OutstandingRewardToPay` (r:1 w:1)
	/// Proof: `NodeManager::OutstandingRewardToPay` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::RewardPot` (r:0 w:1)
	/// Proof: `NodeManager::RewardPot` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	fn on_initialise_with_new_reward_period() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `549`
		//  Estimated: `1525`
		// Minimum execution time: 42_371_000 picoseconds.
		Weight::from_parts(43_451_000, 1525)
			.saturating_add(T::DbWeight::get().reads(8_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `NodeManager::RewardEnabled` (r:1 w:0)
	/// Proof: `NodeManager::RewardEnabled` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::RewardPeriod` (r:1 w:0)
	/// Proof: `NodeManager::RewardPeriod` (`max_values`: Some(1), `max_size`: Some(40), added: 535, mode: `MaxEncodedLen`)
	fn on_initialise_no_reward_period() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `387`
		//  Estimated: `1525`
		// Minimum execution time: 11_600_000 picoseconds.
		Weight::from_parts(12_030_000, 1525)
			.saturating_add(T::DbWeight::get().reads(2_u64))
	}
	/// Storage: `NodeManager::NodeRegistry` (r:1 w:0)
	/// Proof: `NodeManager::NodeRegistry` (`max_values`: None, `max_size`: Some(191), added: 2666, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::RewardPeriod` (r:1 w:0)
	/// Proof: `NodeManager::RewardPeriod` (`max_values`: Some(1), `max_size`: Some(40), added: 535, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::NodeUptime` (r:1 w:1)
	/// Proof: `NodeManager::NodeUptime` (`max_values`: None, `max_size`: Some(100), added: 2575, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::TotalUptime` (r:1 w:1)
	/// Proof: `NodeManager::TotalUptime` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	fn offchain_submit_heartbeat() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `892`
		//  Estimated: `3656`
		// Minimum execution time: 60_641_000 picoseconds.
		Weight::from_parts(61_272_000, 3656)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `NodeManager::NodeRegistrar` (r:1 w:0)
	/// Proof: `NodeManager::NodeRegistrar` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::NodeRegistry` (r:1 w:1)
	/// Proof: `NodeManager::NodeRegistry` (`max_values`: None, `max_size`: Some(191), added: 2666, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::SigningKeyToNodeId` (r:1 w:1)
	/// Proof: `NodeManager::SigningKeyToNodeId` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::NextNodeSerialNumber` (r:1 w:1)
	/// Proof: `NodeManager::NextNodeSerialNumber` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::OwnedNodesCount` (r:1 w:1)
	/// Proof: `NodeManager::OwnedNodesCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::TotalRegisteredNodes` (r:1 w:1)
	/// Proof: `NodeManager::TotalRegisteredNodes` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::OwnedNodes` (r:0 w:1)
	/// Proof: `NodeManager::OwnedNodes` (`max_values`: None, `max_size`: Some(96), added: 2571, mode: `MaxEncodedLen`)
	fn signed_register_node() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `505`
		//  Estimated: `3656`
		// Minimum execution time: 164_424_000 picoseconds.
		Weight::from_parts(165_764_000, 3656)
			.saturating_add(T::DbWeight::get().reads(8_u64))
			.saturating_add(T::DbWeight::get().writes(6_u64))
	}
	/// Storage: `NodeManager::NodeRegistrar` (r:1 w:0)
	/// Proof: `NodeManager::NodeRegistrar` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::OwnedNodes` (r:64 w:64)
	/// Proof: `NodeManager::OwnedNodes` (`max_values`: None, `max_size`: Some(96), added: 2571, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::NodeRegistry` (r:64 w:64)
	/// Proof: `NodeManager::NodeRegistry` (`max_values`: None, `max_size`: Some(191), added: 2666, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::SigningKeyToNodeId` (r:64 w:0)
	/// Proof: `NodeManager::SigningKeyToNodeId` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::OwnedNodesCount` (r:1 w:1)
	/// Proof: `NodeManager::OwnedNodesCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::TotalRegisteredNodes` (r:1 w:1)
	/// Proof: `NodeManager::TotalRegisteredNodes` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// The range of component `b` is `[1, 64]`.
	fn deregister_nodes(b: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `576 + b * (222 ±0)`
		//  Estimated: `3517 + b * (2666 ±0)`
		// Minimum execution time: 53_031_000 picoseconds.
		Weight::from_parts(24_896_267, 3517)
			// Standard Error: 19_932
			.saturating_add(Weight::from_parts(25_878_183, 0).saturating_mul(b.into()))
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().reads((3_u64).saturating_mul(b.into())))
			.saturating_add(T::DbWeight::get().writes(2_u64))
			.saturating_add(T::DbWeight::get().writes((2_u64).saturating_mul(b.into())))
			.saturating_add(Weight::from_parts(0, 2666).saturating_mul(b.into()))
	}
	/// Storage: `NodeManager::NodeRegistrar` (r:1 w:0)
	/// Proof: `NodeManager::NodeRegistrar` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::OwnedNodes` (r:64 w:64)
	/// Proof: `NodeManager::OwnedNodes` (`max_values`: None, `max_size`: Some(96), added: 2571, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::NodeRegistry` (r:64 w:64)
	/// Proof: `NodeManager::NodeRegistry` (`max_values`: None, `max_size`: Some(191), added: 2666, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::SigningKeyToNodeId` (r:64 w:0)
	/// Proof: `NodeManager::SigningKeyToNodeId` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::OwnedNodesCount` (r:1 w:1)
	/// Proof: `NodeManager::OwnedNodesCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::TotalRegisteredNodes` (r:1 w:1)
	/// Proof: `NodeManager::TotalRegisteredNodes` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// The range of component `b` is `[1, 64]`.
	fn signed_deregister_nodes(b: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `576 + b * (222 ±0)`
		//  Estimated: `3517 + b * (2666 ±0)`
		// Minimum execution time: 163_944_000 picoseconds.
		Weight::from_parts(136_788_404, 3517)
			// Standard Error: 18_949
			.saturating_add(Weight::from_parts(26_309_380, 0).saturating_mul(b.into()))
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().reads((3_u64).saturating_mul(b.into())))
			.saturating_add(T::DbWeight::get().writes(2_u64))
			.saturating_add(T::DbWeight::get().writes((2_u64).saturating_mul(b.into())))
			.saturating_add(Weight::from_parts(0, 2666).saturating_mul(b.into()))
	}
	/// Storage: `NodeManager::NodeRegistrar` (r:1 w:0)
	/// Proof: `NodeManager::NodeRegistrar` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::NodeRegistry` (r:1 w:1)
	/// Proof: `NodeManager::NodeRegistry` (`max_values`: None, `max_size`: Some(191), added: 2666, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::SigningKeyToNodeId` (r:2 w:1)
	/// Proof: `NodeManager::SigningKeyToNodeId` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	fn update_signing_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `597`
		//  Estimated: `6100`
		// Minimum execution time: 40_851_000 picoseconds.
		Weight::from_parts(41_311_000, 6100)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	
	fn top_up_reward_pot() -> Weight {
		Weight::from_parts(50_000_000, 3656)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	// One storage write to `HalvingEnabled` + one event.
	fn set_halving_enabled() -> Weight {
		Weight::from_parts(15_000_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	// Per node: 1 NodeRegistry read (validate), 1 NodeUptime mutate (write).
	// Plus 1 TotalUptime mutate, 1 RewardPeriod read, 1 Timestamp read,
	// signature verification (~50M ps), and the BTreeSet dedup.
	fn heartbeat_for_owned_nodes(b: u32, ) -> Weight {
		Weight::from_parts(60_000_000, 3656)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
			.saturating_add(Weight::from_parts(30_000_000, 0).saturating_mul(b.into()))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(b.into())))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(b.into())))
	}
	// One storage write to `LockSchedule` + one event.
	fn set_admin_config_lock_schedule() -> Weight {
		Weight::from_parts(15_000_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	// One storage write to `ForfeitureDestination` + one event.
	fn set_admin_config_forfeiture_destination() -> Weight {
		Weight::from_parts(15_000_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	// Reads: LockedRewards, LockSchedule, Timestamp, ForfeitureDestination,
	// 3 account balances (pot, owner, forfeiture destination). Writes: up to
	// two `Currency::transfer`s out of the pot, LockedRewards,
	// TotalLockedRewards.
	fn withdraw_rewards() -> Weight {
		Weight::from_parts(80_000_000, 6196)
			.saturating_add(T::DbWeight::get().reads(7_u64))
			.saturating_add(T::DbWeight::get().writes(5_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `NodeManager::NodeRegistrar` (r:1 w:0)
	/// Proof: `NodeManager::NodeRegistrar` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::NodeRegistry` (r:1 w:1)
	/// Proof: `NodeManager::NodeRegistry` (`max_values`: None, `max_size`: Some(191), added: 2666, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::SigningKeyToNodeId` (r:1 w:1)
	/// Proof: `NodeManager::SigningKeyToNodeId` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::NextNodeSerialNumber` (r:1 w:1)
	/// Proof: `NodeManager::NextNodeSerialNumber` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::AutoStakeDurationSec` (r:1 w:0)
	/// Proof: `NodeManager::AutoStakeDurationSec` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::OwnedNodesCount` (r:1 w:1)
	/// Proof: `NodeManager::OwnedNodesCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::TotalRegisteredNodes` (r:1 w:1)
	/// Proof: `NodeManager::TotalRegisteredNodes` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::OwnedNodes` (r:0 w:1)
	/// Proof: `NodeManager::OwnedNodes` (`max_values`: None, `max_size`: Some(96), added: 2571, mode: `MaxEncodedLen`)
	fn register_node() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `433`
		//  Estimated: `3656`
		// Minimum execution time: 67_881_000 picoseconds.
		Weight::from_parts(84_332_000, 3656)
			.saturating_add(RocksDbWeight::get().reads(8_u64))
			.saturating_add(RocksDbWeight::get().writes(6_u64))
	}
	/// Storage: `NodeManager::NodeRegistrar` (r:1 w:0)
	/// Proof: `NodeManager::NodeRegistrar` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::NodeRegistry` (r:1 w:1)
	/// Proof: `NodeManager::NodeRegistry` (`max_values`: None, `max_size`: Some(191), added: 2666, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::SigningKeyToNodeId` (r:1 w:1)
	/// Proof: `NodeManager::SigningKeyToNodeId` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::AutoStakeDurationSec` (r:1 w:0)
	/// Proof: `NodeManager::AutoStakeDurationSec` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::OwnedNodesCount` (r:1 w:1)
	/// Proof: `NodeManager::OwnedNodesCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::TotalRegisteredNodes` (r:1 w:1)
	/// Proof: `NodeManager::TotalRegisteredNodes` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::NodeRegistrar` (r:1 w:1)
	/// Proof: `NodeManager::NodeRegistrar` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	fn set_admin_config_registrar() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `360`
		//  Estimated: `1517`
		// Minimum execution time: 19_011_000 picoseconds.
		Weight::from_parts(19_331_000, 1517)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `NodeManager::NextHeartbeatPeriod` (r:1 w:0)
	/// Proof: `NodeManager::NextHeartbeatPeriod` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::RewardPeriod` (r:1 w:0)
	/// Proof: `NodeManager::RewardPeriod` (`max_values`: Some(1), `max_size`: Some(40), added: 535, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::NextRewardPeriodLength` (r:1 w:1)
	/// Proof: `NodeManager::NextRewardPeriodLength` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn set_admin_config_reward_period() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `383`
		//  Estimated: `1525`
		// Minimum execution time: 24_981_000 picoseconds.
		Weight::from_parts(25_611_000, 1525)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `NodeManager::MaxBatchSize` (r:1 w:1)
	/// Proof: `NodeManager::MaxBatchSize` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn set_admin_config_reward_batch_size() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `308`
		//  Estimated: `1489`
		// Minimum execution time: 17_240_000 picoseconds.
		Weight::from_parts(17_821_000, 1489)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `NodeManager::NextRewardPeriodLength` (r:1 w:0)
	/// Proof: `NodeManager::NextRewardPeriodLength` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::NextHeartbeatPeriod` (r:0 w:1)
	/// Proof: `NodeManager::NextHeartbeatPeriod` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn set_admin_config_reward_heartbeat() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `308`
		//  Estimated: `1489`
		// Minimum execution time: 17_410_000 picoseconds.
		Weight::from_parts(17_971_000, 1489)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `NodeManager::NextRewardAmountPerPeriod` (r:0 w:1)
	/// Proof: `NodeManager::NextRewardAmountPerPeriod` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	fn set_admin_config_reward_amount() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 10_070_000 picoseconds.
		Weight::from_parts(10_410_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `NodeManager::RewardEnabled` (r:0 w:1)
	/// Proof: `NodeManager::RewardEnabled` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	fn set_admin_config_reward_enabled() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 10_170_000 picoseconds.
		Weight::from_parts(10_621_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `NodeManager::MinUptimeThreshold` (r:0 w:1)
	/// Proof: `NodeManager::MinUptimeThreshold` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn set_admin_config_min_threshold() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 10_101_000 picoseconds.
		Weight::from_parts(10_830_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `NodeManager::RewardEnabled` (r:1 w:0)
	/// Proof: `NodeManager::RewardEnabled` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::RewardPeriod` (r:1 w:1)
	/// Proof: `NodeManager::RewardPeriod` (`max_values`: Some(1), `max_size`: Some(40), added: 535, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::NextRewardPeriodLength` (r:1 w:0)
	/// Proof: `NodeManager::NextRewardPeriodLength` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::NextHeartbeatPeriod` (r:1 w:0)
	/// Proof: `NodeManager::NextHeartbeatPeriod` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::NextRewardAmountPerPeriod` (r:1 w:0)
	/// Proof: `NodeManager::NextRewardAmountPerPeriod` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::MinUptimeThreshold` (r:1 w:0)
	/// Proof: `NodeManager::MinUptimeThreshold` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::OutstandingRewardToPay` (r:1 w:1)
	/// Proof: `NodeManager::OutstandingRewardToPay` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::RewardPot` (r:0 w:1)
	/// Proof: `NodeManager::RewardPot` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	fn on_initialise_with_new_reward_period() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `549`
		//  Estimated: `1525`
		// Minimum execution time: 42_371_000 picoseconds.
		Weight::from_parts(43_451_000, 1525)
			.saturating_add(RocksDbWeight::get().reads(8_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `NodeManager::RewardEnabled` (r:1 w:0)
	/// Proof: `NodeManager::RewardEnabled` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::RewardPeriod` (r:1 w:0)
	/// Proof: `NodeManager::RewardPeriod` (`max_values`: Some(1), `max_size`: Some(40), added: 535, mode: `MaxEncodedLen`)
	fn on_initialise_no_reward_period() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `387`
		//  Estimated: `1525`
		// Minimum execution time: 11_600_000 picoseconds.
		Weight::from_parts(12_030_000, 1525)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
	}
	/// Storage: `NodeManager::NodeRegistry` (r:1 w:0)
	/// Proof: `NodeManager::NodeRegistry` (`max_values`: None, `max_size`: Some(191), added: 2666, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::RewardPeriod` (r:1 w:0)
	/// Proof: `NodeManager::RewardPeriod` (`max_values`: Some(1), `max_size`: Some(40), added: 535, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::NodeUptime` (r:1 w:1)
	/// Proof: `NodeManager::NodeUptime` (`max_values`: None, `max_size`: Some(100), added: 2575, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::TotalUptime` (r:1 w:1)
	/// Proof: `NodeManager::TotalUptime` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	fn offchain_submit_heartbeat() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `892`
		//  Estimated: `3656`
		// Minimum execution time: 60_641_000 picoseconds.
		Weight::from_parts(61_272_000, 3656)
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `NodeManager::NodeRegistrar` (r:1 w:0)
	/// Proof: `NodeManager::NodeRegistrar` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::NodeRegistry` (r:1 w:1)
	/// Proof: `NodeManager::NodeRegistry` (`max_values`: None, `max_size`: Some(191), added: 2666, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::SigningKeyToNodeId` (r:1 w:1)
	/// Proof: `NodeManager::SigningKeyToNodeId` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::NextNodeSerialNumber` (r:1 w:1)
	/// Proof: `NodeManager::NextNodeSerialNumber` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::OwnedNodesCount` (r:1 w:1)
	/// Proof: `NodeManager::OwnedNodesCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::TotalRegisteredNodes` (r:1 w:1)
	/// Proof: `NodeManager::TotalRegisteredNodes` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::OwnedNodes` (r:0 w:1)
	/// Proof: `NodeManager::OwnedNodes` (`max_values`: None, `max_size`: Some(96), added: 2571, mode: `MaxEncodedLen`)
	fn signed_register_node() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `505`
		//  Estimated: `3656`
		// Minimum execution time: 164_424_000 picoseconds.
		Weight::from_parts(165_764_000, 3656)
			.saturating_add(RocksDbWeight::get().reads(8_u64))
			.saturating_add(RocksDbWeight::get().writes(6_u64))
	}
	/// Storage: `NodeManager::NodeRegistrar` (r:1 w:0)
	/// Proof: `NodeManager::NodeRegistrar` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::OwnedNodes` (r:64 w:64)
	/// Proof: `NodeManager::OwnedNodes` (`max_values`: None, `max_size`: Some(96), added: 2571, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::NodeRegistry` (r:64 w:64)
	/// Proof: `NodeManager::NodeRegistry` (`max_values`: None, `max_size`: Some(191), added: 2666, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::SigningKeyToNodeId` (r:64 w:0)
	/// Proof: `NodeManager::SigningKeyToNodeId` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::OwnedNodesCount` (r:1 w:1)
	/// Proof: `NodeManager::OwnedNodesCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::TotalRegisteredNodes` (r:1 w:1)
	/// Proof: `NodeManager::TotalRegisteredNodes` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// The range of component `b` is `[1, 64]`.
	fn deregister_nodes(b: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `576 + b * (222 ±0)`
		//  Estimated: `3517 + b * (2666 ±0)`
		// Minimum execution time: 53_031_000 picoseconds.
		Weight::from_parts(24_896_267, 3517)
			// Standard Error: 19_932
			.saturating_add(Weight::from_parts(25_878_183, 0).saturating_mul(b.into()))
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().reads((3_u64).saturating_mul(b.into())))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
			.saturating_add(RocksDbWeight::get().writes((2_u64).saturating_mul(b.into())))
			.saturating_add(Weight::from_parts(0, 2666).saturating_mul(b.into()))
	}
	/// Storage: `NodeManager::NodeRegistrar` (r:1 w:0)
	/// Proof: `NodeManager::NodeRegistrar` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::OwnedNodes` (r:64 w:64)
	/// Proof: `NodeManager::OwnedNodes` (`max_values`: None, `max_size`: Some(96), added: 2571, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::NodeRegistry` (r:64 w:64)
	/// Proof: `NodeManager::NodeRegistry` (`max_values`: None, `max_size`: Some(191), added: 2666, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::SigningKeyToNodeId` (r:64 w:0)
	/// Proof: `NodeManager::SigningKeyToNodeId` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::OwnedNodesCount` (r:1 w:1)
	/// Proof: `NodeManager::OwnedNodesCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::TotalRegisteredNodes` (r:1 w:1)
	/// Proof: `NodeManager::TotalRegisteredNodes` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// The range of component `b` is `[1, 64]`.
	fn signed_deregister_nodes(b: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `576 + b * (222 ±0)`
		//  Estimated: `3517 + b * (2666 ±0)`
		// Minimum execution time: 163_944_000 picoseconds.
		Weight::from_parts(136_788_404, 3517)
			// Standard Error: 18_949
			.saturating_add(Weight::from_parts(26_309_380, 0).saturating_mul(b.into()))
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().reads((3_u64).saturating_mul(b.into())))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
			.saturating_add(RocksDbWeight::get().writes((2_u64).saturating_mul(b.into())))
			.saturating_add(Weight::from_parts(0, 2666).saturating_mul(b.into()))
	}
	/// Storage: `NodeManager::NodeRegistrar` (r:1 w:0)
	/// Proof: `NodeManager::NodeRegistrar` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::NodeRegistry` (r:1 w:1)
	/// Proof: `NodeManager::NodeRegistry` (`max_values`: None, `max_size`: Some(191), added: 2666, mode: `MaxEncodedLen`)
	/// Storage: `NodeManager::SigningKeyToNodeId` (r:2 w:1)
	/// Proof: `NodeManager::SigningKeyToNodeId` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	fn update_signing_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `597`
		//  Estimated: `6100`
		// Minimum execution time: 40_851_000 picoseconds.
		Weight::from_parts(41_311_000, 6100)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	fn top_up_reward_pot() -> Weight {
		Weight::from_parts(50_000_000, 3656)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	fn set_halving_enabled() -> Weight {
		Weight::from_parts(15_000_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	fn heartbeat_for_owned_nodes(b: u32, ) -> Weight {
		Weight::from_parts(60_000_000, 3656)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
			.saturating_add(Weight::from_parts(30_000_000, 0).saturating_mul(b.into()))
			.saturating_add(RocksDbWeight::get().reads((1_u64).saturating_mul(b.into())))
			.saturating_add(RocksDbWeight::get().writes((1_u64).saturating_mul(b.into())))
	}
	fn set_admin_config_lock_schedule() -> Weight {
		Weight::from_parts(15_000_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	fn set_admin_config_forfeiture_destination() -> Weight {
		Weight::from_parts(15_000_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	fn withdraw_rewards() -> Weight {
		Weight::from_parts(80_000_000, 6196)
			.saturating_add(RocksDbWeight::get().reads(7_u64))
			.saturating_add(RocksDbWeight::get().writes(5_u64))
	}
}
