// Copyright 2024-2025 Forecasting Technologies LTD.
//
// This file is part of Predictor.
//
// Predictor is free software: you can redistribute it and/or modify it
// under the terms of the GNU General Public License as published by the
// Free Software Foundation, either version 3 of the License, or (at
// your option) any later version.
//
// Predictor is distributed in the hope that it will be useful, but
// WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
// General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Predictor. If not, see <https://www.gnu.org/licenses/>.

#![cfg_attr(not(feature = "std"), no_std)]

extern crate alloc;

#[cfg(feature = "runtime-benchmarks")]
mod benchmarking;
mod mock;
mod tests;
pub mod weights;

pub use pallet::*;

pub const WITHDRAW_FEES_CONTEXT: &[u8] = b"neo_swap::withdraw_fees_context";
pub const EXIT_CONTEXT: &[u8] = b"neo_swap::exit_context";
pub const JOIN_CONTEXT: &[u8] = b"neo_swap::join_context";

#[frame_support::pallet]
pub mod pallet {
    use crate::{weights::SignedWeightInfo, EXIT_CONTEXT, JOIN_CONTEXT, WITHDRAW_FEES_CONTEXT};
    use alloc::{boxed::Box, vec::Vec};
    use frame_support::{
        dispatch::{DispatchResult, DispatchResultWithPostInfo, GetDispatchInfo},
        ensure,
        pallet_prelude::*,
        traits::{IsSubType, StorageVersion},
    };
    use frame_system::{
        ensure_signed,
        pallet_prelude::{BlockNumberFor, OriginFor},
    };
    use pallet_pm_market_commons::MarketCommonsPalletApi;
    use parity_scale_codec::{Decode, Encode};
    use sp_avn_common::{verify_signature, InnerCallValidator, Proof};
    use sp_runtime::{
        traits::{Dispatchable, IdentifyAccount, Member, Saturating, Verify},
        SaturatedConversion,
    };

    #[pallet::config]
    pub trait Config: frame_system::Config + pallet_pm_neo_swaps::Config {
        /// Weights generated by benchmarks.
        type WeightInfo: SignedWeightInfo;

        #[pallet::constant]
        type SignedTxLifetime: Get<u32>;

        type Public: IdentifyAccount<AccountId = Self::AccountId>;

        /// The signature type used by accounts/transactions.
        type Signature: Verify<Signer = Self::Public>
            + Member
            + Decode
            + Encode
            + From<sp_core::sr25519::Signature>
            + TypeInfo;

        /// The overarching call type.
        type RuntimeCall: Parameter
            + Dispatchable<RuntimeOrigin = <Self as frame_system::Config>::RuntimeOrigin>
            + IsSubType<Call<Self>>
            + From<Call<Self>>
            + GetDispatchInfo
            + From<frame_system::Call<Self>>;
    }

    /// The current storage version.
    const STORAGE_VERSION: StorageVersion = StorageVersion::new(0);

    type BalanceOf<T> = pallet_pm_neo_swaps::BalanceOf<T>;
    type MarketIdOf<T> = pallet_pm_neo_swaps::MarketIdOf<T>;

    #[pallet::pallet]
    #[pallet::storage_version(STORAGE_VERSION)]
    pub struct Pallet<T>(_);

    #[pallet::error]
    pub enum Error<T> {
        /// The sender is not the signer of the transaction.
        SenderIsNotSigner,
        /// Signed transaction has failed validation.
        UnauthorizedSignedTransaction,
        /// The signed transaction has expired.
        SignedTransactionExpired,
    }

    #[pallet::call]
    impl<T: Config> Pallet<T> {
        #[pallet::call_index(0)]
        #[pallet::weight(<T as Config>::WeightInfo::signed_join(max_amounts_in.len().saturated_into()))]
        #[frame_support::transactional]
        pub fn signed_join(
            origin: OriginFor<T>,
            proof: Proof<T::Signature, T::AccountId>,
            #[pallet::compact] market_id: MarketIdOf<T>,
            #[pallet::compact] pool_shares_amount: BalanceOf<T>,
            max_amounts_in: Vec<BalanceOf<T>>,
            block_number: BlockNumberFor<T>,
        ) -> DispatchResultWithPostInfo {
            let who = ensure_signed(origin)?;
            ensure!(who == proof.signer, Error::<T>::SenderIsNotSigner);
            Self::ensure_not_expired(block_number)?;

            let encoded_payload = encode_signed_join_params::<T>(
                &proof.relayer,
                &market_id,
                &pool_shares_amount,
                &max_amounts_in,
                &block_number,
            );

            ensure!(
                verify_signature::<T::Signature, T::AccountId>(&proof, &encoded_payload).is_ok(),
                Error::<T>::UnauthorizedSignedTransaction
            );

            let asset_count =
                <T as pallet_pm_neo_swaps::Config>::MarketCommons::market(&market_id)?.outcomes();
            let asset_count_usize: usize = asset_count.into();
            let _: u32 = max_amounts_in
                .len()
                .try_into()
                .map_err(|_| pallet_pm_neo_swaps::Error::<T>::NarrowingConversion)?;
            ensure!(
                max_amounts_in.len() == asset_count_usize,
                pallet_pm_neo_swaps::Error::<T>::IncorrectVecLen
            );

            pallet_pm_neo_swaps::Pallet::<T>::join(
                frame_system::RawOrigin::Signed(who).into(),
                market_id,
                pool_shares_amount,
                max_amounts_in,
            )?;

            Ok(().into())
        }

        #[pallet::call_index(1)]
        #[pallet::weight(<T as Config>::WeightInfo::signed_withdraw_fees())]
        #[frame_support::transactional]
        pub fn signed_withdraw_fees(
            origin: OriginFor<T>,
            proof: Proof<T::Signature, T::AccountId>,
            #[pallet::compact] market_id: MarketIdOf<T>,
            block_number: BlockNumberFor<T>,
        ) -> DispatchResultWithPostInfo {
            let who = ensure_signed(origin)?;
            ensure!(who == proof.signer, Error::<T>::SenderIsNotSigner);
            Self::ensure_not_expired(block_number)?;

            let encoded_payload =
                encode_signed_withdraw_fees_params::<T>(&proof.relayer, &market_id, &block_number);

            ensure!(
                verify_signature::<T::Signature, T::AccountId>(&proof, &encoded_payload).is_ok(),
                Error::<T>::UnauthorizedSignedTransaction
            );

            pallet_pm_neo_swaps::Pallet::<T>::withdraw_fees(
                frame_system::RawOrigin::Signed(who).into(),
                market_id,
            )?;

            Ok(().into())
        }

        #[pallet::call_index(2)]
        #[pallet::weight(<T as Config>::WeightInfo::signed_exit(min_amounts_out.len().saturated_into()))]
        #[frame_support::transactional]
        pub fn signed_exit(
            origin: OriginFor<T>,
            proof: Proof<T::Signature, T::AccountId>,
            #[pallet::compact] market_id: MarketIdOf<T>,
            #[pallet::compact] pool_shares_amount_out: BalanceOf<T>,
            min_amounts_out: Vec<BalanceOf<T>>,
            block_number: BlockNumberFor<T>,
        ) -> DispatchResultWithPostInfo {
            let who = ensure_signed(origin)?;
            ensure!(who == proof.signer, Error::<T>::SenderIsNotSigner);
            Self::ensure_not_expired(block_number)?;

            let encoded_payload = encode_signed_exit_params::<T>(
                &proof.relayer,
                &market_id,
                &pool_shares_amount_out,
                &min_amounts_out,
                &block_number,
            );

            ensure!(
                verify_signature::<T::Signature, T::AccountId>(&proof, &encoded_payload).is_ok(),
                Error::<T>::UnauthorizedSignedTransaction
            );

            let asset_count =
                <T as pallet_pm_neo_swaps::Config>::MarketCommons::market(&market_id)?.outcomes();
            let asset_count_u32: u32 = asset_count.into();
            let min_amounts_out_len: u32 = min_amounts_out
                .len()
                .try_into()
                .map_err(|_| pallet_pm_neo_swaps::Error::<T>::NarrowingConversion)?;
            ensure!(
                min_amounts_out_len == asset_count_u32,
                pallet_pm_neo_swaps::Error::<T>::IncorrectVecLen
            );

            pallet_pm_neo_swaps::Pallet::<T>::exit(
                frame_system::RawOrigin::Signed(who).into(),
                market_id,
                pool_shares_amount_out,
                min_amounts_out,
            )?;

            Ok(().into())
        }
    }

    impl<T: Config> Pallet<T> {
        fn ensure_not_expired(block_number: BlockNumberFor<T>) -> DispatchResult {
            ensure!(
                block_number.saturating_add(<T as Config>::SignedTxLifetime::get().into()) >
                    frame_system::Pallet::<T>::block_number(),
                Error::<T>::SignedTransactionExpired
            );
            Ok(())
        }

        pub fn get_encoded_call_param(
            call: &<T as Config>::RuntimeCall,
        ) -> Option<(&Proof<T::Signature, T::AccountId>, Vec<u8>)> {
            let call = match call.is_sub_type() {
                Some(call) => call,
                None => return None,
            };

            match call {
                Call::signed_join {
                    ref proof,
                    ref market_id,
                    ref pool_shares_amount,
                    ref max_amounts_in,
                    ref block_number,
                } => {
                    let encoded_data = encode_signed_join_params::<T>(
                        &proof.relayer,
                        market_id,
                        pool_shares_amount,
                        max_amounts_in,
                        block_number,
                    );

                    Some((proof, encoded_data))
                },
                Call::signed_exit {
                    ref proof,
                    ref market_id,
                    ref pool_shares_amount_out,
                    ref min_amounts_out,
                    ref block_number,
                } => {
                    let encoded_data = encode_signed_exit_params::<T>(
                        &proof.relayer,
                        market_id,
                        pool_shares_amount_out,
                        min_amounts_out,
                        block_number,
                    );

                    Some((proof, encoded_data))
                },
                Call::signed_withdraw_fees { ref proof, ref market_id, ref block_number } => {
                    let encoded_data = encode_signed_withdraw_fees_params::<T>(
                        &proof.relayer,
                        market_id,
                        block_number,
                    );

                    Some((proof, encoded_data))
                },
                _ => None,
            }
        }
    }

    pub fn encode_signed_join_params<T: Config>(
        relayer: &T::AccountId,
        market_id: &MarketIdOf<T>,
        pool_shares: &BalanceOf<T>,
        max_amounts_in: &Vec<BalanceOf<T>>,
        block_number: &BlockNumberFor<T>,
    ) -> Vec<u8> {
        (JOIN_CONTEXT, relayer, market_id, pool_shares, max_amounts_in, block_number).encode()
    }

    pub fn encode_signed_withdraw_fees_params<T: Config>(
        relayer: &T::AccountId,
        market_id: &MarketIdOf<T>,
        block_number: &BlockNumberFor<T>,
    ) -> Vec<u8> {
        (WITHDRAW_FEES_CONTEXT, relayer, market_id, block_number).encode()
    }

    pub fn encode_signed_exit_params<T: Config>(
        relayer: &T::AccountId,
        market_id: &MarketIdOf<T>,
        pool_shares: &BalanceOf<T>,
        min_amounts_out: &Vec<BalanceOf<T>>,
        block_number: &BlockNumberFor<T>,
    ) -> Vec<u8> {
        (EXIT_CONTEXT, relayer, market_id, pool_shares, min_amounts_out, block_number).encode()
    }

    impl<T: Config> InnerCallValidator for Pallet<T> {
        type Call = <T as Config>::RuntimeCall;

        fn signature_is_valid(call: &Box<Self::Call>) -> bool {
            if let Some((proof, signed_payload)) = Self::get_encoded_call_param(call) {
                return verify_signature::<T::Signature, T::AccountId>(
                    proof,
                    signed_payload.as_slice(),
                )
                .is_ok()
            }

            false
        }
    }
}
