[dependencies]
common-primitives = { workspace = true, optional = true }
frame-benchmarking = { workspace = true, optional = true }
frame-support = { workspace = true }
frame-system = { workspace = true }
orml-traits = { workspace = true, optional = true }
pallet-avn = { workspace = true, optional = true }
pallet-prediction-markets = { workspace = true }
pallet-pm-market-commons = { workspace = true }
pallet-timestamp = { workspace = true, optional = true }
parity-scale-codec = { workspace = true, features = ["derive", "max-encoded-len"] }
prediction-market-primitives = { workspace = true }
scale-info = { workspace = true, features = ["derive"] }
sp-avn-common = { workspace = true }
sp-core = { workspace = true }
sp-runtime = { workspace = true }

[dev-dependencies]
orml-traits = { workspace = true, features = ["std"] }
pallet-balances = { workspace = true, features = ["std"] }
pallet-pm-authorized = { workspace = true, features = ["std"] }
pallet-pm-court = { workspace = true, features = ["std"] }
pallet-pm-global-disputes = { workspace = true, features = ["std"] }
sp-avn-common = { workspace = true, features = ["test-utils"] }
sp-arithmetic = { workspace = true, features = ["std"] }
sp-io = { workspace = true }

[features]
default = ["std"]
runtime-benchmarks = [
    "common-primitives",
    "frame-benchmarking/runtime-benchmarks",
    "frame-support/runtime-benchmarks",
    "frame-system/runtime-benchmarks",
    "orml-traits",
    "pallet-avn",
    "pallet-prediction-markets/runtime-benchmarks",
    "pallet-timestamp/runtime-benchmarks",
]
std = [
    "common-primitives?/std",
    "frame-benchmarking?/std",
    "frame-support/std",
    "frame-system/std",
    "orml-traits?/std",
    "pallet-avn?/std",
    "pallet-prediction-markets/std",
    "pallet-pm-market-commons/std",
    "pallet-timestamp?/std",
    "parity-scale-codec/std",
    "prediction-market-primitives/std",
    "scale-info/std",
    "sp-avn-common/std",
    "sp-core/std",
    "sp-runtime/std",
]
try-runtime = [
    "frame-support/try-runtime",
]

[package]
authors.workspace = true
edition.workspace = true
name = "pallet-pm-signed-prediction-markets"
version = "0.2.2"
