[package]
authors = ["Aventus systems team"]
edition = { workspace = true }
name = "common-primitives"
version.workspace = true

[dependencies]
frame-support = { workspace = true }
parity-scale-codec = { workspace = true, features = [
  "derive",
  "max-encoded-len",
] }
sp-core = { workspace = true }
sp-runtime = { workspace = true }


[features]
default = ["std"]
std = [
  "frame-support/std",
  "parity-scale-codec/std",
  "sp-core/std",
  "sp-runtime/std",
]
