// Copyright 2024-2025 Forecasting Technologies LTD.
//
// This file is part of Zeitgeist.
//
// Zeitgeist is free software: you can redistribute it and/or modify it
// under the terms of the GNU General Public License as published by the
// Free Software Foundation, either version 3 of the License, or (at
// your option) any later version.
//
// Zeitgeist is distributed in the hope that it will be useful, but
// WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
// General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Zeitgeist. If not, see <https://www.gnu.org/licenses/>.

#![doc = include_str!("../README.md")]
#![cfg_attr(not(feature = "std"), no_std)]

extern crate alloc;

mod benchmarking;
mod mock;
mod tests;
pub mod weights;
pub mod zeitgeist_adapters;

pub use pallet::*;

#[frame_support::pallet]
mod pallet {
    pub const BUY: &[u8] = b"buy outcome tokens";
    pub const SELL: &[u8] = b"sell outcome tokens";

    use crate::weights::SignedWeightInfo;
    use alloc::{vec, vec::Vec};
    use core::marker::PhantomData;
    use frame_support::{
        dispatch::GetDispatchInfo,
        ensure,
        pallet_prelude::*,
        traits::{IsSubType, StorageVersion},
    };
    use frame_system::{
        ensure_signed,
        pallet_prelude::{BlockNumberFor, OriginFor},
    };
    use orml_traits::MultiCurrency;
    use pallet_pm_market_commons::MarketCommonsPalletApi;
    #[cfg(feature = "runtime-benchmarks")]
    use prediction_market_primitives::traits::{CompleteSetOperationsApi, DeployPoolApi};
    use prediction_market_primitives::{
        orderbook::{Order, OrderId},
        traits::{HybridRouterAmmApi, HybridRouterOrderbookApi},
        types::Asset,
    };
    use scale_info::prelude::boxed::Box;
    use sp_avn_common::{verify_signature, InnerCallValidator, Proof};
    use sp_runtime::{
        traits::{Dispatchable, IdentifyAccount, Verify},
        SaturatedConversion,
    };
    use zeitgeist_hybrid_router::Strategy;

    #[pallet::config]
    pub trait Config:
        frame_system::Config
        + zeitgeist_hybrid_router::Config<
            AssetManager = crate::zeitgeist_adapters::PredictorAssetManagerAdapter<Self>,
            MarketCommons = crate::zeitgeist_adapters::PredictorMarketCommonsAdapter<Self>,
            Amm = crate::zeitgeist_adapters::PredictorAmmAdapter<Self>,
            Orderbook = crate::zeitgeist_adapters::PredictorOrderbookAdapter<Self>,
        >
    {
        /// The API to handle different asset classes.
        type AssetManager: MultiCurrency<Self::AccountId, CurrencyId = AssetOf<Self>>;

        #[cfg(feature = "runtime-benchmarks")]
        type AmmPoolDeployer: DeployPoolApi<
            AccountId = AccountIdOf<Self>,
            Balance = BalanceOf<Self>,
            MarketId = MarketIdOf<Self>,
        >;

        #[cfg(feature = "runtime-benchmarks")]
        type CompleteSetOperations: CompleteSetOperationsApi<
            AccountId = AccountIdOf<Self>,
            Balance = BalanceOf<Self>,
            MarketId = MarketIdOf<Self>,
        >;

        /// The identifier of individual markets.
        type MarketCommons: MarketCommonsPalletApi<
            AccountId = Self::AccountId,
            BlockNumber = BlockNumberFor<Self>,
            Balance = BalanceOf<Self>,
        >;

        /// The API to handle the Automated Market Maker (AMM).
        type Amm: HybridRouterAmmApi<
            AccountId = AccountIdOf<Self>,
            MarketId = MarketIdOf<Self>,
            Asset = AssetOf<Self>,
            Balance = BalanceOf<Self>,
        >;

        /// The API to handle the order book.
        type Orderbook: HybridRouterOrderbookApi<
            AccountId = AccountIdOf<Self>,
            MarketId = MarketIdOf<Self>,
            Balance = BalanceOf<Self>,
            Asset = AssetOf<Self>,
            Order = OrderOf<Self>,
            OrderId = OrderId,
        >;

        /// Weights generated by benchmarks.
        type WeightInfo: SignedWeightInfo;

        type Public: IdentifyAccount<AccountId = Self::AccountId>;

        /// The signature type used by accounts/transactions.
        type Signature: Verify<Signer = Self::Public>
            + Member
            + Decode
            + Encode
            + From<sp_core::sr25519::Signature>
            + TypeInfo;

        /// The overarching call type.
        type RuntimeCall: Parameter
            + Dispatchable<RuntimeOrigin = <Self as frame_system::Config>::RuntimeOrigin>
            + IsSubType<Call<Self>>
            + From<Call<Self>>
            + GetDispatchInfo
            + From<frame_system::Call<Self>>;
    }

    /// The current storage version.
    const STORAGE_VERSION: StorageVersion = StorageVersion::new(0);

    pub(crate) type AssetOf<T> = Asset<MarketIdOf<T>>;
    pub(crate) type AccountIdOf<T> = <T as frame_system::Config>::AccountId;
    pub(crate) type BalanceOf<T> =
        <<T as Config>::AssetManager as MultiCurrency<AccountIdOf<T>>>::Balance;
    pub(crate) type MarketIdOf<T> =
        <<T as Config>::MarketCommons as MarketCommonsPalletApi>::MarketId;
    pub(crate) type OrderOf<T> = Order<AccountIdOf<T>, BalanceOf<T>, MarketIdOf<T>>;

    #[pallet::storage]
    #[pallet::getter(fn market_nonces)]
    pub type MarketNonces<T: Config> = StorageDoubleMap<
        _,
        Blake2_128Concat,
        T::AccountId,
        Blake2_128Concat,
        MarketIdOf<T>,
        u64,
        ValueQuery,
    >;

    #[pallet::pallet]
    #[pallet::storage_version(STORAGE_VERSION)]
    pub struct Pallet<T>(PhantomData<T>);

    #[pallet::error]
    pub enum Error<T> {
        /// The sender is not the signer of the transaction.
        SenderIsNotSigner,
        /// Signed transaction has failed validation.
        UnauthorizedSignedTransaction,
    }

    #[pallet::call]
    impl<T: Config> Pallet<T> {
        /// Routes a signed buy order through the Zeitgeist hybrid-router pallet.
        #[pallet::call_index(2)]
        #[pallet::weight(<T as Config>::WeightInfo::signed_buy(*asset_count as u32, orders.len().saturated_into::<u32>()))]
        #[frame_support::transactional]
        #[allow(clippy::too_many_arguments)]
        pub fn signed_buy(
            origin: OriginFor<T>,
            proof: Proof<T::Signature, T::AccountId>,
            market_id: MarketIdOf<T>,
            #[pallet::compact] asset_count: u16,
            asset: AssetOf<T>,
            #[pallet::compact] amount_in: BalanceOf<T>,
            #[pallet::compact] max_price: BalanceOf<T>,
            orders: Vec<OrderId>,
            strategy: Strategy,
        ) -> DispatchResultWithPostInfo {
            let who = ensure_signed(origin)?;
            ensure!(who == proof.signer, Error::<T>::SenderIsNotSigner);

            let market_nonce = MarketNonces::<T>::get(&proof.signer, &market_id);

            let signed_payload = encode_signed_buy_params::<T>(
                &proof.relayer,
                market_nonce,
                &market_id,
                &asset_count,
                &asset,
                &amount_in,
                &max_price,
                &orders,
                &strategy,
            );

            ensure!(
                verify_signature::<T::Signature, T::AccountId>(&proof, &signed_payload).is_ok(),
                Error::<T>::UnauthorizedSignedTransaction
            );

            zeitgeist_hybrid_router::Pallet::<T>::buy(
                frame_system::RawOrigin::Signed(who.clone()).into(),
                market_id.clone(),
                asset_count,
                crate::zeitgeist_adapters::to_zeitgeist_asset(asset),
                amount_in,
                max_price,
                orders,
                strategy,
            )?;

            MarketNonces::<T>::mutate(who, market_id, |nonce| *nonce += 1);
            Ok(().into())
        }

        /// Routes a signed sell order through the Zeitgeist hybrid-router pallet.
        #[pallet::call_index(3)]
        #[pallet::weight(<T as Config>::WeightInfo::signed_sell(*asset_count as u32, orders.len().saturated_into::<u32>()))]
        #[frame_support::transactional]
        #[allow(clippy::too_many_arguments)]
        pub fn signed_sell(
            origin: OriginFor<T>,
            proof: Proof<T::Signature, T::AccountId>,
            market_id: MarketIdOf<T>,
            #[pallet::compact] asset_count: u16,
            asset: AssetOf<T>,
            #[pallet::compact] amount_in: BalanceOf<T>,
            #[pallet::compact] min_price: BalanceOf<T>,
            orders: Vec<OrderId>,
            strategy: Strategy,
        ) -> DispatchResultWithPostInfo {
            let who = ensure_signed(origin)?;
            ensure!(who == proof.signer, Error::<T>::SenderIsNotSigner);

            let market_nonce = MarketNonces::<T>::get(&proof.signer, &market_id);

            let signed_payload = encode_signed_sell_params::<T>(
                &proof.relayer,
                market_nonce,
                &market_id,
                &asset_count,
                &asset,
                &amount_in,
                &min_price,
                &orders,
                &strategy,
            );

            ensure!(
                verify_signature::<T::Signature, T::AccountId>(&proof, &signed_payload).is_ok(),
                Error::<T>::UnauthorizedSignedTransaction
            );

            zeitgeist_hybrid_router::Pallet::<T>::sell(
                frame_system::RawOrigin::Signed(who.clone()).into(),
                market_id.clone(),
                asset_count,
                crate::zeitgeist_adapters::to_zeitgeist_asset(asset),
                amount_in,
                min_price,
                orders,
                strategy,
            )?;

            MarketNonces::<T>::mutate(who, market_id, |nonce| *nonce += 1);
            Ok(().into())
        }
    }

    impl<T> Pallet<T>
    where
        T: Config,
    {
        pub fn get_encoded_call_param(
            call: &<T as Config>::RuntimeCall,
        ) -> Option<(&Proof<T::Signature, T::AccountId>, Vec<u8>)> {
            let call = match call.is_sub_type() {
                Some(call) => call,
                None => return None,
            };

            match call {
                Call::signed_buy {
                    ref proof,
                    ref market_id,
                    ref asset_count,
                    ref asset,
                    ref amount_in,
                    ref max_price,
                    ref orders,
                    ref strategy,
                } => {
                    let nonce = Self::market_nonces(&proof.signer, market_id);
                    let encoded_data = encode_signed_buy_params::<T>(
                        &proof.relayer,
                        nonce,
                        market_id,
                        asset_count,
                        asset,
                        amount_in,
                        max_price,
                        orders,
                        strategy,
                    );

                    Some((proof, encoded_data))
                },
                Call::signed_sell {
                    ref proof,
                    ref market_id,
                    ref asset_count,
                    ref asset,
                    ref amount_in,
                    ref min_price,
                    ref orders,
                    ref strategy,
                } => {
                    let nonce = Self::market_nonces(&proof.signer, market_id);
                    let encoded_data = encode_signed_sell_params::<T>(
                        &proof.relayer,
                        nonce,
                        market_id,
                        asset_count,
                        asset,
                        amount_in,
                        min_price,
                        orders,
                        strategy,
                    );

                    Some((proof, encoded_data))
                },
                _ => None,
            }
        }
    }

    pub fn encode_signed_buy_params<T: Config>(
        relayer: &T::AccountId,
        nonce: u64,
        market_id: &MarketIdOf<T>,
        asset_count: &u16,
        asset: &AssetOf<T>,
        amount_in: &BalanceOf<T>,
        max_price: &BalanceOf<T>,
        orders: &Vec<OrderId>,
        strategy: &Strategy,
    ) -> Vec<u8> {
        (
            BUY,
            relayer.clone(),
            nonce,
            market_id,
            asset_count,
            asset,
            amount_in,
            max_price,
            orders,
            strategy,
        )
            .encode()
    }

    pub fn encode_signed_sell_params<T: Config>(
        relayer: &T::AccountId,
        nonce: u64,
        market_id: &MarketIdOf<T>,
        asset_count: &u16,
        asset: &AssetOf<T>,
        amount_in: &BalanceOf<T>,
        min_price: &BalanceOf<T>,
        orders: &Vec<OrderId>,
        strategy: &Strategy,
    ) -> Vec<u8> {
        (
            SELL,
            relayer.clone(),
            nonce,
            market_id,
            asset_count,
            asset,
            amount_in,
            min_price,
            orders,
            strategy,
        )
            .encode()
    }

    impl<T: Config> InnerCallValidator for Pallet<T> {
        type Call = <T as Config>::RuntimeCall;

        fn signature_is_valid(call: &Box<Self::Call>) -> bool {
            if let Some((proof, signed_payload)) = Self::get_encoded_call_param(call) {
                return verify_signature::<T::Signature, T::AccountId>(
                    proof,
                    signed_payload.as_slice(),
                )
                .is_ok();
            }

            false
        }
    }
}
